google_calendar_link: "https://calendar.google.com/calendar/embed?ctz=America%2FChicago&src=c2lncHdueUBnbWFpbC5jb20&showPrint=0&showCalendars=0&mode=WEEK"

title: SIGPwny
twitter_username: SIGPwny
github_username: sigpwny
youtube_link: https://www.youtube.com/channel/UC3fWGYI7-Kt3Gi0aOIZMicg
discord_link: https://discord.gg/cWcZ6a9

collections:
  meetings:
    output: true
    permalink: /:collection/:path
  events:
    output: true
    permalink: /:collection/:path
  redirects:
    output: true
    permalink: /:path
  writeups:
    output: true
    permalink: /:collection/:path

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

sass:
  style: compressed

permalink: pretty
exclude: [vendor]
plugins:
  - jekyll-sitemap
